typography_spectrum: 0.648398
color:
  brandColors:
    - '#00ccff'
    - '#000000'
    - '#fbffff'
    - '#005d74'
    - '#818181'
  brandStrength: 0
  lightness: 1
  saturation: 0.1875
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.18332
analytics:
  google: null
  facebook: null
  twitter: null
name: Audioforge
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Blog
    url: 'http://blog.audiogorge.org'
    type: external
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: Audioforge Labs Inc.
purpose: []
