name: Audioforge
favicon: null
layout_spectrum: 0.12877705204300582
typography_spectrum: 0.24994740705005825
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.17060976079665124
  lightness: 0.5991864681709558
  saturation: 0.9026064765639603
  rhythmicContrast: 0.434405219508335
purpose: []
