name: Audioforge
favicon: null
layout_spectrum: 0.6838111
typography_spectrum: 0.648398
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Audio apps for iOS and Mac OS X
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#00ccff'
    - '#000000'
    - '#fbffff'
    - '#005d74'
    - '#818181'
  brandStrength: 0.5
  lightness: 0.5991864681709558
  saturation: 0.9026064765639603
  rhythmicContrast: 0.434405219508335
purpose: []
